### ISSUE TITLE
Target netstandard2.0 (instead of netcoreapp2.0)

### ISSUE THREAD

**Issue by davidni** [ThreeMammals/Rafty#12]
## Expected Behavior / New Feature
This is needed in order to have Ocelot target netstandard2.0, thereby facilitating much wider adoption. This is a trivial change to make and I will submit a PR shortly.

**Comment by TomPallister** [comment]
@davidni sounds good, re Ocelot conversation happy to accept a PR.

**Comment by TomPallister** [comment]
@davidni OK Ive merged this and will get a release out asap.

**Comment by davidni** [comment]
Thanks Tom, sounds good. Any ETA or rough idea when you might be able to release?

**Comment by TomPallister** [comment]
@davidni I have just pushed 0.4.3 of rafty. Will be on nuget soon. This won’t be a simple upgrade in Ocelot because rafty api has changed. Have a look and if it is too much work let me know.

**Comment by TomPallister** [comment]
Something went wrong with release process. I need to investigate.

**Comment by TomPallister** [comment]
Ok fixed

**Comment by davidni** [comment]
Awesome, and I've submitted my PR to Ocelot to consume this. Thanks for the quick turnaround!
